services:
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    ports:
      - "8081:80"
    
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

  app:
    build: .
    ports:
      - "9000:9000"
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:
networks:
  app-network:
    driver: bridge